version: "3.8"

services:
    php:
        build: .
        ports:
            - 80:80
        volumes:
            - ./:/var/www/html
        depends_on: 
            - db
    db:
        image: mysql:5.7
        ports:
            - 3307:3306
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=vacation
            - MYSQL_USER=epignosis
            - MYSQL_PASSWORD=epignosis
        volumes:
            - ./sql:/docker-entrypoint-initdb.d
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_HOST=db
            - PMA_USER=root
            - PMA_PASSWORD=root
            - MYSQL_ROOT_PASSWORD=root 
        ports:
            - 8080:80
        depends_on:
            - db
