Search.appendIndex(
    [
                {
            "fqsen": "\\takisrs\\Controllers\\ApplicationController",
            "name": "ApplicationController",
            "summary": "Application\u0020Controller",
            "url": "classes/takisrs-Controllers-ApplicationController.html"
        },                {
            "fqsen": "\\takisrs\\Controllers\\ApplicationController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Retrieves\u0020and\u0020returns\u0020the\u0020list\u0020of\u0020applications\u0020of\u0020the\u0020authorized\u0020user",
            "url": "classes/takisrs-Controllers-ApplicationController.html#method_index"
        },                {
            "fqsen": "\\takisrs\\Controllers\\ApplicationController\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Creates\u0020a\u0020new\u0020application\u0020and\u0020returns\u0020the\u0020result\u0020of\u0020the\u0020operation",
            "url": "classes/takisrs-Controllers-ApplicationController.html#method_create"
        },                {
            "fqsen": "\\takisrs\\Controllers\\ApplicationController\u003A\u003Aapprove\u0028\u0029",
            "name": "approve",
            "summary": "Approves\u0020an\u0020application",
            "url": "classes/takisrs-Controllers-ApplicationController.html#method_approve"
        },                {
            "fqsen": "\\takisrs\\Controllers\\ApplicationController\u003A\u003Areject\u0028\u0029",
            "name": "reject",
            "summary": "Rejects\u0020an\u0020application",
            "url": "classes/takisrs-Controllers-ApplicationController.html#method_reject"
        },                {
            "fqsen": "\\takisrs\\Controllers\\AuthController",
            "name": "AuthController",
            "summary": "Auth\u0020Controller",
            "url": "classes/takisrs-Controllers-AuthController.html"
        },                {
            "fqsen": "\\takisrs\\Controllers\\AuthController\u003A\u003Alogin\u0028\u0029",
            "name": "login",
            "summary": "Login",
            "url": "classes/takisrs-Controllers-AuthController.html#method_login"
        },                {
            "fqsen": "\\takisrs\\Controllers\\UserController",
            "name": "UserController",
            "summary": "User\u0020Controller",
            "url": "classes/takisrs-Controllers-UserController.html"
        },                {
            "fqsen": "\\takisrs\\Controllers\\UserController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Retrieves\u0020and\u0020returns\u0020the\u0020list\u0020of\u0020all\u0020users",
            "url": "classes/takisrs-Controllers-UserController.html#method_index"
        },                {
            "fqsen": "\\takisrs\\Controllers\\UserController\u003A\u003Asingle\u0028\u0029",
            "name": "single",
            "summary": "Retrieves\u0020and\u0020returns\u0020the\u0020fields\u0020of\u0020the\u0020requested\u0020user",
            "url": "classes/takisrs-Controllers-UserController.html#method_single"
        },                {
            "fqsen": "\\takisrs\\Controllers\\UserController\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Creates\u0020a\u0020new\u0020user",
            "url": "classes/takisrs-Controllers-UserController.html#method_create"
        },                {
            "fqsen": "\\takisrs\\Controllers\\UserController\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "Updates\u0020an\u0020user",
            "url": "classes/takisrs-Controllers-UserController.html#method_update"
        },                {
            "fqsen": "\\takisrs\\Core\\Authenticator",
            "name": "Authenticator",
            "summary": "A\u0020class\u0020that\u0020handles\u0020the\u0020tasks\u0020related\u0020to\u0020JWT\u0020authorization",
            "url": "classes/takisrs-Core-Authenticator.html"
        },                {
            "fqsen": "\\takisrs\\Core\\Authenticator\u003A\u003AgetToken\u0028\u0029",
            "name": "getToken",
            "summary": "Encodes\u0020the\u0020given\u0020payload\u0020and\u0020returns\u0020a\u0020JWT\u0020token",
            "url": "classes/takisrs-Core-Authenticator.html#method_getToken"
        },                {
            "fqsen": "\\takisrs\\Core\\Authenticator\u003A\u003AdecodeToken\u0028\u0029",
            "name": "decodeToken",
            "summary": "Receives\u0020a\u0020token,\u0020decodes\u0020it\u0020and\u0020returns\u0020the\u0020data",
            "url": "classes/takisrs-Core-Authenticator.html#method_decodeToken"
        },                {
            "fqsen": "\\takisrs\\Core\\Authenticator\u003A\u003AALLOWED_ALGORITHMS",
            "name": "ALLOWED_ALGORITHMS",
            "summary": "Allowed\u0020algorithms\u0020for\u0020decoding\u0020a\u0020token",
            "url": "classes/takisrs-Core-Authenticator.html#constant_ALLOWED_ALGORITHMS"
        },                {
            "fqsen": "\\takisrs\\Core\\Controller",
            "name": "Controller",
            "summary": "Base\u0020Controller\u0020class",
            "url": "classes/takisrs-Core-Controller.html"
        },                {
            "fqsen": "\\takisrs\\Core\\Controller\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Base\u0020controller\u0020constructor",
            "url": "classes/takisrs-Core-Controller.html#method___construct"
        },                {
            "fqsen": "\\takisrs\\Core\\Controller\u003A\u003A\u0024request",
            "name": "request",
            "summary": "The\u0020request\u0020instance",
            "url": "classes/takisrs-Core-Controller.html#property_request"
        },                {
            "fqsen": "\\takisrs\\Core\\Controller\u003A\u003A\u0024response",
            "name": "response",
            "summary": "The\u0020response\u0020instance",
            "url": "classes/takisrs-Core-Controller.html#property_response"
        },                {
            "fqsen": "\\takisrs\\Core\\HttpException",
            "name": "HttpException",
            "summary": "A\u0020simple\u0020HttpException\u0020class",
            "url": "classes/takisrs-Core-HttpException.html"
        },                {
            "fqsen": "\\takisrs\\Core\\HttpException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "HttpException\u0020constructor",
            "url": "classes/takisrs-Core-HttpException.html#method___construct"
        },                {
            "fqsen": "\\takisrs\\Core\\Model",
            "name": "Model",
            "summary": "Base\u0020Controller\u0020class",
            "url": "classes/takisrs-Core-Model.html"
        },                {
            "fqsen": "\\takisrs\\Core\\Model\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/takisrs-Core-Model.html#method___construct"
        },                {
            "fqsen": "\\takisrs\\Core\\Model\u003A\u003Afind\u0028\u0029",
            "name": "find",
            "summary": "Accepts\u0020an\u0020id\u0020and\u0020retrieves\u0020the\u0020corresponding\u0020record\u0020from\u0020the\u0020database",
            "url": "classes/takisrs-Core-Model.html#method_find"
        },                {
            "fqsen": "\\takisrs\\Core\\Model\u003A\u003AfindOneBy\u0028\u0029",
            "name": "findOneBy",
            "summary": "Retrieves\u0020a\u0020record\u0020from\u0020the\u0020database",
            "url": "classes/takisrs-Core-Model.html#method_findOneBy"
        },                {
            "fqsen": "\\takisrs\\Core\\Model\u003A\u003AfindBy\u0028\u0029",
            "name": "findBy",
            "summary": "Retrieves\u0020a\u0020list\u0020of\u0020records\u0020of\u0020the\u0020database\u0020and\u0020return\u0020an\u0020object\u0020for\u0020each\u0020record",
            "url": "classes/takisrs-Core-Model.html#method_findBy"
        },                {
            "fqsen": "\\takisrs\\Core\\Model\u003A\u003AfindAll\u0028\u0029",
            "name": "findAll",
            "summary": "Retrieves\u0020all\u0020the\u0020records\u0020of\u0020the\u0020corresponding\u0020table\u0020from\u0020the\u0020database",
            "url": "classes/takisrs-Core-Model.html#method_findAll"
        },                {
            "fqsen": "\\takisrs\\Core\\Model\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Performs\u0020an\u0020insert\u0020query",
            "url": "classes/takisrs-Core-Model.html#method_create"
        },                {
            "fqsen": "\\takisrs\\Core\\Model\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "Performs\u0020an\u0020update\u0020query",
            "url": "classes/takisrs-Core-Model.html#method_update"
        },                {
            "fqsen": "\\takisrs\\Core\\Model\u003A\u003AgetBindParams\u0028\u0029",
            "name": "getBindParams",
            "summary": "Returns\u0020an\u0020array\u0020with\u0020the\u0020pdo\u0020bindings",
            "url": "classes/takisrs-Core-Model.html#method_getBindParams"
        },                {
            "fqsen": "\\takisrs\\Core\\Model\u003A\u003AbuildWhere\u0028\u0029",
            "name": "buildWhere",
            "summary": "Gets\u0020and\u0020array\u0020of\u0020field\u002Dvalue\u0020pairs\u0020and\u0020returns\u0020an\u0020sql\u0020where\u0020clause",
            "url": "classes/takisrs-Core-Model.html#method_buildWhere"
        },                {
            "fqsen": "\\takisrs\\Core\\Model\u003A\u003AmapResultToObject\u0028\u0029",
            "name": "mapResultToObject",
            "summary": "Maps\u0020the\u0020result\u0020of\u0020a\u0020select\u0020query\u0020to\u0020the\u0020corresponding\u0020model",
            "url": "classes/takisrs-Core-Model.html#method_mapResultToObject"
        },                {
            "fqsen": "\\takisrs\\Core\\Model\u003A\u003A\u0024db",
            "name": "db",
            "summary": "An\u0020instance\u0020of\u0020the\u0020mysql\u0020database\u0020PDO\u0020connection",
            "url": "classes/takisrs-Core-Model.html#property_db"
        },                {
            "fqsen": "\\takisrs\\Core\\MySQLConnection",
            "name": "MySQLConnection",
            "summary": "A\u0020class\u0020that\u0020handles\u0020the\u0020mysql\u0020connection",
            "url": "classes/takisrs-Core-MySQLConnection.html"
        },                {
            "fqsen": "\\takisrs\\Core\\MySQLConnection\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor",
            "url": "classes/takisrs-Core-MySQLConnection.html#method___construct"
        },                {
            "fqsen": "\\takisrs\\Core\\MySQLConnection\u003A\u003AgetInstance\u0028\u0029",
            "name": "getInstance",
            "summary": "Returns\u0020the\u0020instance\u0020of\u0020the\u0020MySQLConnection",
            "url": "classes/takisrs-Core-MySQLConnection.html#method_getInstance"
        },                {
            "fqsen": "\\takisrs\\Core\\MySQLConnection\u003A\u003AgetConnection\u0028\u0029",
            "name": "getConnection",
            "summary": "Returns\u0020the\u0020PDO\u0020connection",
            "url": "classes/takisrs-Core-MySQLConnection.html#method_getConnection"
        },                {
            "fqsen": "\\takisrs\\Core\\MySQLConnection\u003A\u003A\u0024instance",
            "name": "instance",
            "summary": "the\u0020MySQLConnection\u0020instance",
            "url": "classes/takisrs-Core-MySQLConnection.html#property_instance"
        },                {
            "fqsen": "\\takisrs\\Core\\MySQLConnection\u003A\u003A\u0024connection",
            "name": "connection",
            "summary": "a\u0020PDO\u0020instance",
            "url": "classes/takisrs-Core-MySQLConnection.html#property_connection"
        },                {
            "fqsen": "\\takisrs\\Core\\Request",
            "name": "Request",
            "summary": "Request\u0020class",
            "url": "classes/takisrs-Core-Request.html"
        },                {
            "fqsen": "\\takisrs\\Core\\Request\u003A\u003AsetUser\u0028\u0029",
            "name": "setUser",
            "summary": "Sets\u0020the\u0020authentication\u0020user",
            "url": "classes/takisrs-Core-Request.html#method_setUser"
        },                {
            "fqsen": "\\takisrs\\Core\\Request\u003A\u003Auser\u0028\u0029",
            "name": "user",
            "summary": "Returns\u0020the\u0020authorized\u0020user\u0020of\u0020the\u0020request",
            "url": "classes/takisrs-Core-Request.html#method_user"
        },                {
            "fqsen": "\\takisrs\\Core\\Request\u003A\u003AsetParam\u0028\u0029",
            "name": "setParam",
            "summary": "Sets\u0020a\u0020route\u0020param",
            "url": "classes/takisrs-Core-Request.html#method_setParam"
        },                {
            "fqsen": "\\takisrs\\Core\\Request\u003A\u003Aparam\u0028\u0029",
            "name": "param",
            "summary": "Retrieves\u0020a\u0020param\u0020from\u0020the\u0020request\u0020according\u0020to\u0020the\u0020provided\u0020key",
            "url": "classes/takisrs-Core-Request.html#method_param"
        },                {
            "fqsen": "\\takisrs\\Core\\Request\u003A\u003AauthorizationToken\u0028\u0029",
            "name": "authorizationToken",
            "summary": "Retrieves\u0020the\u0020authorization\u0020token\u0020of\u0020the\u0020request",
            "url": "classes/takisrs-Core-Request.html#method_authorizationToken"
        },                {
            "fqsen": "\\takisrs\\Core\\Request\u003A\u003Aheader\u0028\u0029",
            "name": "header",
            "summary": "Retrieves\u0020a\u0020header\u0020from\u0020the\u0020request",
            "url": "classes/takisrs-Core-Request.html#method_header"
        },                {
            "fqsen": "\\takisrs\\Core\\Request\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "Retrieves\u0020a\u0020\u0024_GET\u0020parameter",
            "url": "classes/takisrs-Core-Request.html#method_get"
        },                {
            "fqsen": "\\takisrs\\Core\\Request\u003A\u003Apost\u0028\u0029",
            "name": "post",
            "summary": "Retrieves\u0020a\u0020\u0024_POST\u0020parameter",
            "url": "classes/takisrs-Core-Request.html#method_post"
        },                {
            "fqsen": "\\takisrs\\Core\\Request\u003A\u003Abody\u0028\u0029",
            "name": "body",
            "summary": "Retrieves\u0020a\u0020parameter\u0020from\u0020the\u0020json\u0020request\u0020body",
            "url": "classes/takisrs-Core-Request.html#method_body"
        },                {
            "fqsen": "\\takisrs\\Core\\Request\u003A\u003AgetMethod\u0028\u0029",
            "name": "getMethod",
            "summary": "Returns\u0020the\u0020request\u0020method\u0020\u0028POST,\u0020GET\u0029",
            "url": "classes/takisrs-Core-Request.html#method_getMethod"
        },                {
            "fqsen": "\\takisrs\\Core\\Request\u003A\u003AgetUri\u0028\u0029",
            "name": "getUri",
            "summary": "Returns\u0020the\u0020request\u0020uri",
            "url": "classes/takisrs-Core-Request.html#method_getUri"
        },                {
            "fqsen": "\\takisrs\\Core\\Request\u003A\u003Avalidate\u0028\u0029",
            "name": "validate",
            "summary": "A\u0020simple\u0020validation\u0020method\u0020for\u0020all\u0020request\u0020params\u0020\u0028get,\u0020post,\u0020body\u0029",
            "url": "classes/takisrs-Core-Request.html#method_validate"
        },                {
            "fqsen": "\\takisrs\\Core\\Request\u003A\u003Aclean\u0028\u0029",
            "name": "clean",
            "summary": "Cleans\u0020the\u0020provided\u0020data",
            "url": "classes/takisrs-Core-Request.html#method_clean"
        },                {
            "fqsen": "\\takisrs\\Core\\Request\u003A\u003A\u0024authenticatedUser",
            "name": "authenticatedUser",
            "summary": "The\u0020object\u0020of\u0020the\u0020authenticated\u0020user",
            "url": "classes/takisrs-Core-Request.html#property_authenticatedUser"
        },                {
            "fqsen": "\\takisrs\\Core\\Request\u003A\u003A\u0024params",
            "name": "params",
            "summary": "Keeps\u0020url\u0020parameters",
            "url": "classes/takisrs-Core-Request.html#property_params"
        },                {
            "fqsen": "\\takisrs\\Core\\Response",
            "name": "Response",
            "summary": "Response\u0020class",
            "url": "classes/takisrs-Core-Response.html"
        },                {
            "fqsen": "\\takisrs\\Core\\Response\u003A\u003Astatus\u0028\u0029",
            "name": "status",
            "summary": "Sets\u0020the\u0020response\u0020status\u0020code",
            "url": "classes/takisrs-Core-Response.html#method_status"
        },                {
            "fqsen": "\\takisrs\\Core\\Response\u003A\u003Asend\u0028\u0029",
            "name": "send",
            "summary": "Sends\u0020a\u0020response\u0020to\u0020the\u0020client",
            "url": "classes/takisrs-Core-Response.html#method_send"
        },                {
            "fqsen": "\\takisrs\\Core\\Response\u003A\u003Aheaders\u0028\u0029",
            "name": "headers",
            "summary": "The\u0020headers\u0020of\u0020the\u0020response",
            "url": "classes/takisrs-Core-Response.html#method_headers"
        },                {
            "fqsen": "\\takisrs\\Core\\Response\u003A\u003A\u0024code",
            "name": "code",
            "summary": "http\u0020response\u0020status\u0020code",
            "url": "classes/takisrs-Core-Response.html#property_code"
        },                {
            "fqsen": "\\takisrs\\Core\\Router",
            "name": "Router",
            "summary": "Router\u0020class",
            "url": "classes/takisrs-Core-Router.html"
        },                {
            "fqsen": "\\takisrs\\Core\\Router\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Router\u0020constructor",
            "url": "classes/takisrs-Core-Router.html#method___construct"
        },                {
            "fqsen": "\\takisrs\\Core\\Router\u003A\u003ArequireAuth\u0028\u0029",
            "name": "requireAuth",
            "summary": "Checks\u0020if\u0020the\u0020request\u0020is\u0020authorized",
            "url": "classes/takisrs-Core-Router.html#method_requireAuth"
        },                {
            "fqsen": "\\takisrs\\Core\\Router\u003A\u003AaddRoute\u0028\u0029",
            "name": "addRoute",
            "summary": "Registers\u0020a\u0020route",
            "url": "classes/takisrs-Core-Router.html#method_addRoute"
        },                {
            "fqsen": "\\takisrs\\Core\\Router\u003A\u003Apost\u0028\u0029",
            "name": "post",
            "summary": "Registers\u0020a\u0020post\u0020route",
            "url": "classes/takisrs-Core-Router.html#method_post"
        },                {
            "fqsen": "\\takisrs\\Core\\Router\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "Registers\u0020a\u0020get\u0020route",
            "url": "classes/takisrs-Core-Router.html#method_get"
        },                {
            "fqsen": "\\takisrs\\Core\\Router\u003A\u003AconvertPatternToRegex\u0028\u0029",
            "name": "convertPatternToRegex",
            "summary": "Convert\u0020to\u0020regex",
            "url": "classes/takisrs-Core-Router.html#method_convertPatternToRegex"
        },                {
            "fqsen": "\\takisrs\\Core\\Router\u003A\u003AmatchAndExtractParams\u0028\u0029",
            "name": "matchAndExtractParams",
            "summary": "Checks\u0020if\u0020uri\u0020matches\u0020the\u0020pattern\u0020and\u0020extracts\u0020the\u0020params",
            "url": "classes/takisrs-Core-Router.html#method_matchAndExtractParams"
        },                {
            "fqsen": "\\takisrs\\Core\\Router\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "Matches\u0020the\u0020request\u0020with\u0020the\u0020corresponding\u0020controller\/method\u0020and\u0020processes\u0020it",
            "url": "classes/takisrs-Core-Router.html#method_run"
        },                {
            "fqsen": "\\takisrs\\Core\\Router\u003A\u003AREQUIRE_USER",
            "name": "REQUIRE_USER",
            "summary": "",
            "url": "classes/takisrs-Core-Router.html#constant_REQUIRE_USER"
        },                {
            "fqsen": "\\takisrs\\Core\\Router\u003A\u003AREQUIRE_ADMIN",
            "name": "REQUIRE_ADMIN",
            "summary": "",
            "url": "classes/takisrs-Core-Router.html#constant_REQUIRE_ADMIN"
        },                {
            "fqsen": "\\takisrs\\Core\\Router\u003A\u003A\u0024routes",
            "name": "routes",
            "summary": "Keeps\u0020data\u0020about\u0020the\u0020available\u0020routes",
            "url": "classes/takisrs-Core-Router.html#property_routes"
        },                {
            "fqsen": "\\takisrs\\Core\\Router\u003A\u003A\u0024request",
            "name": "request",
            "summary": "",
            "url": "classes/takisrs-Core-Router.html#property_request"
        },                {
            "fqsen": "\\takisrs\\Core\\Router\u003A\u003A\u0024response",
            "name": "response",
            "summary": "",
            "url": "classes/takisrs-Core-Router.html#property_response"
        },                {
            "fqsen": "\\takisrs\\Helpers\\EmailTemplate",
            "name": "EmailTemplate",
            "summary": "Handles\u0020email\u0020templating\u0020and\u0020sending",
            "url": "classes/takisrs-Helpers-EmailTemplate.html"
        },                {
            "fqsen": "\\takisrs\\Helpers\\EmailTemplate\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor",
            "url": "classes/takisrs-Helpers-EmailTemplate.html#method___construct"
        },                {
            "fqsen": "\\takisrs\\Helpers\\EmailTemplate\u003A\u003AloadBody\u0028\u0029",
            "name": "loadBody",
            "summary": "Loads\u0020the\u0020html\u0020content\u0020of\u0020the\u0020template\u0020file",
            "url": "classes/takisrs-Helpers-EmailTemplate.html#method_loadBody"
        },                {
            "fqsen": "\\takisrs\\Helpers\\EmailTemplate\u003A\u003AextractSubject\u0028\u0029",
            "name": "extractSubject",
            "summary": "Extracts\u0020the\u0020email\u0020subject\u0020from\u0020the\u0020title\u0020tag\u0020of\u0020the\u0020html\u0020page",
            "url": "classes/takisrs-Helpers-EmailTemplate.html#method_extractSubject"
        },                {
            "fqsen": "\\takisrs\\Helpers\\EmailTemplate\u003A\u003AreplaceVar\u0028\u0029",
            "name": "replaceVar",
            "summary": "Replaces\u0020a\u0020variable\u0020in\u0020the\u0020html\u0020content\u0020with\u0020the\u0020provided\u0020value",
            "url": "classes/takisrs-Helpers-EmailTemplate.html#method_replaceVar"
        },                {
            "fqsen": "\\takisrs\\Helpers\\EmailTemplate\u003A\u003AreplaceVars\u0028\u0029",
            "name": "replaceVars",
            "summary": "Replaces\u0020all\u0020the\u0020variables\u0020in\u0020the\u0020html\u0020content\u0020of\u0020the\u0020email\u0020template",
            "url": "classes/takisrs-Helpers-EmailTemplate.html#method_replaceVars"
        },                {
            "fqsen": "\\takisrs\\Helpers\\EmailTemplate\u003A\u003AgetSubject\u0028\u0029",
            "name": "getSubject",
            "summary": "Returns\u0020email\u0027s\u0020subject",
            "url": "classes/takisrs-Helpers-EmailTemplate.html#method_getSubject"
        },                {
            "fqsen": "\\takisrs\\Helpers\\EmailTemplate\u003A\u003AgetBody\u0028\u0029",
            "name": "getBody",
            "summary": "Returns\u0020email\u0027s\u0020body",
            "url": "classes/takisrs-Helpers-EmailTemplate.html#method_getBody"
        },                {
            "fqsen": "\\takisrs\\Helpers\\EmailTemplate\u003A\u003Asend\u0028\u0029",
            "name": "send",
            "summary": "Sends\u0020the\u0020email",
            "url": "classes/takisrs-Helpers-EmailTemplate.html#method_send"
        },                {
            "fqsen": "\\takisrs\\Helpers\\EmailTemplate\u003A\u003A\u0024templatePath",
            "name": "templatePath",
            "summary": "The\u0020path\u0020to\u0020the\u0020html\u0020template\u0020file",
            "url": "classes/takisrs-Helpers-EmailTemplate.html#property_templatePath"
        },                {
            "fqsen": "\\takisrs\\Helpers\\EmailTemplate\u003A\u003A\u0024subject",
            "name": "subject",
            "summary": "Email\u0027s\u0020subject",
            "url": "classes/takisrs-Helpers-EmailTemplate.html#property_subject"
        },                {
            "fqsen": "\\takisrs\\Helpers\\EmailTemplate\u003A\u003A\u0024body",
            "name": "body",
            "summary": "Email\u0027s\u0020html\u0020content",
            "url": "classes/takisrs-Helpers-EmailTemplate.html#property_body"
        },                {
            "fqsen": "\\takisrs\\Models\\Application",
            "name": "Application",
            "summary": "Application\u0020Model\u0020class",
            "url": "classes/takisrs-Models-Application.html"
        },                {
            "fqsen": "\\takisrs\\Models\\Application\u003A\u003Auser\u0028\u0029",
            "name": "user",
            "summary": "Returns\u0020application\u0027s\u0020user\u0020object",
            "url": "classes/takisrs-Models-Application.html#method_user"
        },                {
            "fqsen": "\\takisrs\\Models\\Application\u003A\u003AisApproved\u0028\u0029",
            "name": "isApproved",
            "summary": "Returns\u0020true\u0020if\u0020the\u0020application\u0020has\u0020been\u0020approved",
            "url": "classes/takisrs-Models-Application.html#method_isApproved"
        },                {
            "fqsen": "\\takisrs\\Models\\Application\u003A\u003AisRejected\u0028\u0029",
            "name": "isRejected",
            "summary": "Returns\u0020true\u0020if\u0020the\u0020application\u0020has\u0020been\u0020rejected",
            "url": "classes/takisrs-Models-Application.html#method_isRejected"
        },                {
            "fqsen": "\\takisrs\\Models\\Application\u003A\u003Aapprove\u0028\u0029",
            "name": "approve",
            "summary": "Approves\u0020the\u0020application\u0020\u0028Updates\u0020status\u0020to\u0020\u0022approved\u0022\u0029",
            "url": "classes/takisrs-Models-Application.html#method_approve"
        },                {
            "fqsen": "\\takisrs\\Models\\Application\u003A\u003Areject\u0028\u0029",
            "name": "reject",
            "summary": "Rejects\u0020the\u0020application\u0020\u0028Updates\u0020status\u0020to\u0020\u0022rejected\u0022\u0029",
            "url": "classes/takisrs-Models-Application.html#method_reject"
        },                {
            "fqsen": "\\takisrs\\Models\\Application\u003A\u003Adays\u0028\u0029",
            "name": "days",
            "summary": "Returns\u0020the\u0020duration\u0020of\u0020the\u0020vacation\u0020in\u0020days",
            "url": "classes/takisrs-Models-Application.html#method_days"
        },                {
            "fqsen": "\\takisrs\\Models\\Application\u003A\u003ASTATUS_PENDING",
            "name": "STATUS_PENDING",
            "summary": "",
            "url": "classes/takisrs-Models-Application.html#constant_STATUS_PENDING"
        },                {
            "fqsen": "\\takisrs\\Models\\Application\u003A\u003ASTATUS_APPROVED",
            "name": "STATUS_APPROVED",
            "summary": "",
            "url": "classes/takisrs-Models-Application.html#constant_STATUS_APPROVED"
        },                {
            "fqsen": "\\takisrs\\Models\\Application\u003A\u003ASTATUS_REJECTED",
            "name": "STATUS_REJECTED",
            "summary": "",
            "url": "classes/takisrs-Models-Application.html#constant_STATUS_REJECTED"
        },                {
            "fqsen": "\\takisrs\\Models\\Application\u003A\u003A\u0024tableName",
            "name": "tableName",
            "summary": "The\u0020name\u0020of\u0020aplications\u0027\u0020table",
            "url": "classes/takisrs-Models-Application.html#property_tableName"
        },                {
            "fqsen": "\\takisrs\\Models\\Application\u003A\u003A\u0024primaryKey",
            "name": "primaryKey",
            "summary": "The\u0020primary\u0020key\u0020of\u0020aplications\u0020table",
            "url": "classes/takisrs-Models-Application.html#property_primaryKey"
        },                {
            "fqsen": "\\takisrs\\Models\\Application\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "The\u0020fields\u0020that\u0020can\u0020be\u0020filled\u0020in\u0020the\u0020aplications\u0027\u0020database\u0020table",
            "url": "classes/takisrs-Models-Application.html#property_fillable"
        },                {
            "fqsen": "\\takisrs\\Models\\Application\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/takisrs-Models-Application.html#property_id"
        },                {
            "fqsen": "\\takisrs\\Models\\Application\u003A\u003A\u0024userId",
            "name": "userId",
            "summary": "",
            "url": "classes/takisrs-Models-Application.html#property_userId"
        },                {
            "fqsen": "\\takisrs\\Models\\Application\u003A\u003A\u0024dateFrom",
            "name": "dateFrom",
            "summary": "",
            "url": "classes/takisrs-Models-Application.html#property_dateFrom"
        },                {
            "fqsen": "\\takisrs\\Models\\Application\u003A\u003A\u0024dateTo",
            "name": "dateTo",
            "summary": "",
            "url": "classes/takisrs-Models-Application.html#property_dateTo"
        },                {
            "fqsen": "\\takisrs\\Models\\Application\u003A\u003A\u0024reason",
            "name": "reason",
            "summary": "",
            "url": "classes/takisrs-Models-Application.html#property_reason"
        },                {
            "fqsen": "\\takisrs\\Models\\Application\u003A\u003A\u0024status",
            "name": "status",
            "summary": "",
            "url": "classes/takisrs-Models-Application.html#property_status"
        },                {
            "fqsen": "\\takisrs\\Models\\Application\u003A\u003A\u0024createdAt",
            "name": "createdAt",
            "summary": "",
            "url": "classes/takisrs-Models-Application.html#property_createdAt"
        },                {
            "fqsen": "\\takisrs\\Models\\Application\u003A\u003A\u0024modifiedAt",
            "name": "modifiedAt",
            "summary": "",
            "url": "classes/takisrs-Models-Application.html#property_modifiedAt"
        },                {
            "fqsen": "\\takisrs\\Models\\User",
            "name": "User",
            "summary": "User\u0020Model\u0020class",
            "url": "classes/takisrs-Models-User.html"
        },                {
            "fqsen": "\\takisrs\\Models\\User\u003A\u003AisAdmin\u0028\u0029",
            "name": "isAdmin",
            "summary": "Returns\u0020true\u0020if\u0020the\u0020user\u0020is\u0020an\u0020admin",
            "url": "classes/takisrs-Models-User.html#method_isAdmin"
        },                {
            "fqsen": "\\takisrs\\Models\\User\u003A\u003AisUser\u0028\u0029",
            "name": "isUser",
            "summary": "Returns\u0020true\u0020if\u0020the\u0020user\u0020is\u0020a\u0020simple\u0020user",
            "url": "classes/takisrs-Models-User.html#method_isUser"
        },                {
            "fqsen": "\\takisrs\\Models\\User\u003A\u003Aapplications\u0028\u0029",
            "name": "applications",
            "summary": "Returns\u0020an\u0020array\u0020of\u0020user\u0027s\u0020applications",
            "url": "classes/takisrs-Models-User.html#method_applications"
        },                {
            "fqsen": "\\takisrs\\Models\\User\u003A\u003ATYPE_USER",
            "name": "TYPE_USER",
            "summary": "",
            "url": "classes/takisrs-Models-User.html#constant_TYPE_USER"
        },                {
            "fqsen": "\\takisrs\\Models\\User\u003A\u003ATYPE_ADMIN",
            "name": "TYPE_ADMIN",
            "summary": "",
            "url": "classes/takisrs-Models-User.html#constant_TYPE_ADMIN"
        },                {
            "fqsen": "\\takisrs\\Models\\User\u003A\u003A\u0024tableName",
            "name": "tableName",
            "summary": "The\u0020name\u0020of\u0020users\u0027\u0020table",
            "url": "classes/takisrs-Models-User.html#property_tableName"
        },                {
            "fqsen": "\\takisrs\\Models\\User\u003A\u003A\u0024primaryKey",
            "name": "primaryKey",
            "summary": "The\u0020primary\u0020key\u0020of\u0020users\u0027\u0020table",
            "url": "classes/takisrs-Models-User.html#property_primaryKey"
        },                {
            "fqsen": "\\takisrs\\Models\\User\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "The\u0020fields\u0020that\u0020can\u0020be\u0020filled\u0020in\u0020the\u0020users\u0027\u0020database\u0020table",
            "url": "classes/takisrs-Models-User.html#property_fillable"
        },                {
            "fqsen": "\\takisrs\\Models\\User\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/takisrs-Models-User.html#property_id"
        },                {
            "fqsen": "\\takisrs\\Models\\User\u003A\u003A\u0024firstName",
            "name": "firstName",
            "summary": "",
            "url": "classes/takisrs-Models-User.html#property_firstName"
        },                {
            "fqsen": "\\takisrs\\Models\\User\u003A\u003A\u0024lastName",
            "name": "lastName",
            "summary": "",
            "url": "classes/takisrs-Models-User.html#property_lastName"
        },                {
            "fqsen": "\\takisrs\\Models\\User\u003A\u003A\u0024email",
            "name": "email",
            "summary": "",
            "url": "classes/takisrs-Models-User.html#property_email"
        },                {
            "fqsen": "\\takisrs\\Models\\User\u003A\u003A\u0024password",
            "name": "password",
            "summary": "",
            "url": "classes/takisrs-Models-User.html#property_password"
        },                {
            "fqsen": "\\takisrs\\Models\\User\u003A\u003A\u0024type",
            "name": "type",
            "summary": "",
            "url": "classes/takisrs-Models-User.html#property_type"
        },                {
            "fqsen": "\\takisrs\\Models\\User\u003A\u003A\u0024createdAt",
            "name": "createdAt",
            "summary": "",
            "url": "classes/takisrs-Models-User.html#property_createdAt"
        },                {
            "fqsen": "\\takisrs\\Models\\User\u003A\u003A\u0024modifiedAt",
            "name": "modifiedAt",
            "summary": "",
            "url": "classes/takisrs-Models-User.html#property_modifiedAt"
        },                {
            "fqsen": "\\takisrs\\VacationApp",
            "name": "VacationApp",
            "summary": "App\u0027s\u0020main\u0020class",
            "url": "classes/takisrs-VacationApp.html"
        },                {
            "fqsen": "\\takisrs\\VacationApp\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/takisrs-VacationApp.html#method___construct"
        },                {
            "fqsen": "\\takisrs\\VacationApp\u003A\u003AregisterRoutes\u0028\u0029",
            "name": "registerRoutes",
            "summary": "Declares\u0020the\u0020routes\u0020that\u0020the\u0020app\u0020uses.",
            "url": "classes/takisrs-VacationApp.html#method_registerRoutes"
        },                {
            "fqsen": "\\takisrs\\VacationApp\u003A\u003Ainit\u0028\u0029",
            "name": "init",
            "summary": "App\u0027s\u0020main\u0020method.\u0020All\u0020starts\u0020here.",
            "url": "classes/takisrs-VacationApp.html#method_init"
        },                {
            "fqsen": "\\takisrs\\VacationApp\u003A\u003A\u0024request",
            "name": "request",
            "summary": "The\u0020request\u0020object",
            "url": "classes/takisrs-VacationApp.html#property_request"
        },                {
            "fqsen": "\\takisrs\\VacationApp\u003A\u003A\u0024response",
            "name": "response",
            "summary": "The\u0020response\u0020onject",
            "url": "classes/takisrs-VacationApp.html#property_response"
        },                {
            "fqsen": "\\takisrs\\VacationApp\u003A\u003A\u0024router",
            "name": "router",
            "summary": "The\u0020router\u0020object",
            "url": "classes/takisrs-VacationApp.html#property_router"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\takisrs\\Controllers",
            "name": "Controllers",
            "summary": "",
            "url": "namespaces/takisrs-controllers.html"
        },                {
            "fqsen": "\\takisrs\\Core",
            "name": "Core",
            "summary": "",
            "url": "namespaces/takisrs-core.html"
        },                {
            "fqsen": "\\takisrs\\Helpers",
            "name": "Helpers",
            "summary": "",
            "url": "namespaces/takisrs-helpers.html"
        },                {
            "fqsen": "\\takisrs\\Models",
            "name": "Models",
            "summary": "",
            "url": "namespaces/takisrs-models.html"
        },                {
            "fqsen": "\\takisrs",
            "name": "takisrs",
            "summary": "",
            "url": "namespaces/takisrs.html"
        }            ]
);
